title: GeekCode Italia
description: Blog italiano su informatica in generale, programmazione e sicurezza informatica
url: https://tiawrld.github.io/
author:
  name: Mattia Petullo
lang: it
theme: minima
